/* confdefs.h */
#define PACKAGE_NAME "cndrvcups-common"
#define PACKAGE_TARNAME "cndrvcups-common"
#define PACKAGE_VERSION "2.90"
#define PACKAGE_STRING "cndrvcups-common 2.90"
#define PACKAGE_BUGREPORT "krichter722@aol.de"
#define PACKAGE_URL ""
#define PACKAGE "cndrvcups-common"
#define VERSION "2.90"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
